export const quotes = {
  easy: {
    science: [
      "The important thing is not to stop questioning",
      "Science allows us to ask questions and find answers",
      "Learning science is like solving the mysteries of nature",
      "The whole of science is nothing more than a refinement of everyday thinking",
      "The universe is under no obligation to make sense to you",
    ],
    "web development": [
      "Web development is not just about writing code, it's about creating experiences",
      "Building websites is like creating doors to new worlds",
      "A great website is one that solves problems for its users",
      "In web development, creativity and functionality go hand in hand",
      "A website should be an interactive experience that adds value to its users",
    ],
    psychology: [
      "The unexamined life is not worth living",
      "Understanding yourself is the first step to understanding others",
      "Happiness begins with a healthy mind",
      "Psychology is the science of behavior and mind, embracing all aspects of conscious and unconscious experience",
      "The human mind is a powerful thing—if you understand how it works, you can unlock limitless potential",
    ],
    IT: [
      "Information technology is a tool, not the solution",
      "IT connects people, ideas, and solutions",
      "Technology makes things easier, but it’s up to us to make them better",
      "IT empowers individuals to achieve more and think beyond the limits",
      "Technology has revolutionized how we live and work, but it's up to humanity to create its future",
    ],
    ALML: [
      "Artificial intelligence is the new electricity",
      "AI can make our lives easier if we use it wisely",
      "Machine learning is like teaching machines how to think",
      "AI is not the future; it is the present that shapes our future",
      "Machine learning is the key to unlocking a new wave of technological innovation",
    ],
    IOT: [
      "The future of IoT is endless possibilities",
      "Smart devices make our lives smarter",
      "IoT connects the physical world to the digital world",
      "IoT is the bridge between the real world and the digital age",
      "In the future, everything will be connected through IoT, revolutionizing the way we interact with the world",
    ],
    GK: [
      "Knowledge is power",
      "Curiosity is the first step to learning",
      "Sharing knowledge is the best way to grow it",
      "The pursuit of knowledge has no end, and the more we know, the more we realize how much there is to learn",
      "To be truly educated is to constantly seek new knowledge and embrace the unknown",
    ],
    sociology: [
      "Sociology is the study of society and human behavior",
      "Understanding society helps us understand ourselves",
      "Social bonds are what hold communities together",
      "The way societies evolve and change defines the world we live in",
      "Sociology helps us understand the invisible forces shaping human behavior",
    ],
  },
  medium: {
    science: [
      "Science is the belief in the ignorance of the experts",
      "Every discovery begins with a question",
      "Science evolves by challenging existing ideas",
      "The pursuit of knowledge in science is a journey, not a destination",
      "Science is not about answering questions but about uncovering new ones that lead to deeper understanding",
    ],
    "web development": [
      "The best way to predict the future of web development is to create it",
      "A website’s true value lies in how well it serves its users",
      "Web development bridges creativity and technology",
      "A great web developer crafts not just code, but solutions that empower people",
      "In web development, everything is a learning experience; it’s about adapting and evolving",
    ],
    psychology: [
      "Psychology is the study of behavior, not just the study of mind",
      "Our thoughts shape our reality",
      "Emotions are powerful drivers of human behavior",
      "The mind is a maze, and understanding it is the key to unlocking human potential",
      "Psychology is not just about treating problems, but understanding how to enhance the human experience",
    ],
    IT: [
      "The great myth of our age is that IT is separate from the business",
      "IT bridges gaps between challenges and solutions",
      "Technology shapes the way businesses grow",
      "Information technology is the backbone of the modern world, driving everything from communication to innovation",
      "IT is the engine that powers industries forward, propelling us into a connected and automated future",
    ],
    ALML: [
      "The future belongs to those who embrace artificial intelligence and machine learning",
      "AI can help solve problems humans can’t solve alone",
      "Machine learning enables systems to learn from past experiences",
      "Artificial intelligence can solve complex problems faster than any human mind can",
      "Machine learning and AI are not just innovations, they are the foundation for the next revolution in technology",
    ],
    IOT: [
      "The Internet of Things is transforming the way we live and work",
      "IoT enables automation in everyday life",
      "The possibilities of IoT expand as technology evolves",
      "With IoT, the power to control and analyze data in real time is within our hands",
      "IoT is revolutionizing industries and everyday life by seamlessly connecting the digital and physical worlds",
    ],
    GK: [
      "An investment in knowledge pays the best interest",
      "Knowledge is the key to making informed decisions",
      "The more you explore, the more you learn",
      "True wisdom is the ability to use knowledge effectively in every aspect of life",
      "A thirst for knowledge is a journey with no end, only discoveries",
    ],
    sociology: [
      "Sociology helps us understand the complex relationship between individuals and society",
      "Social change begins with understanding societal structures",
      "Sociology connects individual actions to larger patterns",
      "Understanding the social fabric of society allows us to build better communities",
      "Sociology unveils the forces that bind us together as a society and can drive progress",
    ],
  },
  hard: {
    science: [
      "Science is a way of thinking much more than it is a body of knowledge",
      "True science embraces uncertainty and curiosity",
      "Science is not just about answers but the journey of discovery",
      "Scientific progress is not linear, but a series of breakthroughs and failures that lead to truth",
      "Science shows us the beauty of the universe, not just in what we know, but in what we are yet to discover",
    ],
    "web development": [
      "Design is not just what it looks like and feels like. Design is how it works",
      "A great design considers both functionality and aesthetics",
      "The web is dynamic; adaptability is key in development",
      "In web development, the difference between good and great is in the details",
      "A well-designed website isn’t just about how it looks—it’s about how it makes people feel and how it works",
    ],
    psychology: [
      "Mental health is not a destination, but a process",
      "Our subconscious mind often influences our decisions",
      "Understanding emotions is crucial for personal growth",
      "Psychology teaches us that mental health is just as important as physical health, and both need attention",
      "The journey of understanding human emotions is one of the most profound paths we can take",
    ],
    IT: [
      "IT is not just about hardware and software, it’s about how we use technology to solve problems",
      "IT strategy is the backbone of innovation",
      "Effective IT management drives organizational success",
      "In IT, success is not just about implementing technology, but about leveraging it for meaningful change",
      "IT is the invisible thread that connects every part of our modern lives, from business to entertainment",
    ],
    ALML: [
      "Machine learning is a key element of AI, where systems learn from data and improve over time",
      "AI thrives on data and algorithms to predict and adapt",
      "Deep learning mimics the neural networks of the human brain",
      "The evolution of machine learning is transforming every industry, from healthcare to finance",
      "AI and machine learning are unlocking possibilities that were once beyond our imagination",
    ],
    IOT: [
      "In IoT, we have a combination of software, sensors, and the internet working together",
      "IoT relies on seamless communication between devices",
      "Edge computing is crucial for IoT’s future scalability",
      "IoT allows us to optimize and automate processes across industries, bringing new levels of efficiency",
      "The future of IoT is incredibly bright, with innovations that will reshape our daily lives",
    ],
    GK: [
      "The more that you read, the more things you will know",
      "Critical thinking comes from a foundation of knowledge",
      "True wisdom is knowing how to apply knowledge",
      "Knowledge empowers individuals to make informed decisions and change the world around them",
      "Knowledge, when shared, has the power to ignite change and progress",
    ],
    sociology: [
      "The study of sociology is not just about understanding society, but about changing it",
      "Sociology examines the unseen rules that govern human interaction",
      "Understanding societal systems leads to informed social change",
      "Sociology enables us to understand the structures that shape our lives and guides us toward a better future",
      "Sociology sheds light on the inequalities of society, helping to drive justice and equality",
    ],
  },
};
